project_id = "usvexhegaiufodtstkxp"

[functions.get-school-holidays]
verify_jwt = false

[functions.search-stocks]
verify_jwt = false

[functions.get-stock-price]
verify_jwt = false

[functions.v2-process-automations]
verify_jwt = false

[functions.v2-daily-snapshot]
verify_jwt = false
